import React from 'react';
import { Routes, Route, Navigate } from 'react-router-dom';
import Layout from './components/Layout';
import { ErrorBoundary } from './components/ErrorBoundary';
import { ToastProvider } from './components/Toast';
import Login from './pages/Login';
import Dashboard from './pages/Dashboard';
import Campaigns from './pages/Campaigns';
import CampaignDetail from './pages/CampaignDetail';
import Contacts from './pages/Contacts';
import ContactDetail from './pages/ContactDetail';
import Templates from './pages/Templates';
import TemplateDetail from './pages/TemplateDetail';
import Analytics from './pages/Analytics';
import ABTests from './pages/ABTests';
import ABTestDetail from './pages/ABTestDetail';
import Integrations from './pages/Integrations';
import IntegrationDetail from './pages/IntegrationDetail';
import Team from './pages/Team';
import TeamMemberDetail from './pages/TeamMemberDetail';
import AIAssistant from './pages/AIAssistant';
import Settings from './pages/Settings';
import Sequences from './pages/Sequences';
import SequenceDetail from './pages/SequenceDetail';
import Meetings from './pages/Meetings';
import MeetingDetail from './pages/MeetingDetail';
import Tasks from './pages/Tasks';
import TaskDetail from './pages/TaskDetail';
import Reports from './pages/Reports';
import ReportDetail from './pages/ReportDetail';
import Notifications from './pages/Notifications';
import AILeadScorer from './pages/AILeadScorer';
import AILeadScoreDetail from './pages/AILeadScoreDetail';
import AIPersonalization from './pages/AIPersonalization';
import AIPersonalizationDetail from './pages/AIPersonalizationDetail';
import AIBestTime from './pages/AIBestTime';
import AIBestTimeDetail from './pages/AIBestTimeDetail';
import AIObjections from './pages/AIObjections';
import AIObjectionDetail from './pages/AIObjectionDetail';
import AIPipelineForecast from './pages/AIPipelineForecast';
import AIPipelineForecastDetail from './pages/AIPipelineForecastDetail';
import PasswordReset from './pages/PasswordReset';
import AIWarmupScheduler from './pages/AIWarmupScheduler';
import AICompetitiveIntel from './pages/AICompetitiveIntel';
import AIPlaybookLearner from './pages/AIPlaybookLearner';
import AIProspectResearch from './pages/AIProspectResearch';
import AIDealMomentum from './pages/AIDealMomentum';
import AIObjectionPredictor from './pages/AIObjectionPredictor';
import AIReplyTriage from './pages/AIReplyTriage';
import Deals from './pages/Deals';
import CustomViewsPage from './pages/CustomViewsPage';
import { AuthProvider, useAuth } from './hooks/useAuth';

import CodexCustomVizFeature from './pages/CodexCustomVizFeature';
import CodexOperationsFeature from './pages/CodexOperationsFeature';
// Apply pass 7: Gap pages (backlog wiring)
import GapAiAccountTierScoringIcp from './pages/GapAiAccountTierScoringIcp';
import GapAiCompetitorWinLossAnalysis from './pages/GapAiCompetitorWinLossAnalysis';
import GapAiLiveConversationCoachingCalls from './pages/GapAiLiveConversationCoachingCalls';
import GapAiMultilingualOutreachGeneration from './pages/GapAiMultilingualOutreachGeneration';
import GapAutoGeneratedCompetitorBattlecardsWeb from './pages/GapAutoGeneratedCompetitorBattlecardsWeb';
import GapDeeperEnrichmentSalesforceEinsteinLinkedin from './pages/GapDeeperEnrichmentSalesforceEinsteinLinkedin';
import GapLimitedCustomFieldAutomationData from './pages/GapLimitedCustomFieldAutomationData';
import GapMultiChannelAssetLibraryVideo from './pages/GapMultiChannelAssetLibraryVideo';
import GapQbrExecutiveSummaryBuilder from './pages/GapQbrExecutiveSummaryBuilder';
import GapRealTimeMeetingTranscriptAnalysis from './pages/GapRealTimeMeetingTranscriptAnalysis';
import GapRevenueAttributionModelingBeyondSimple from './pages/GapRevenueAttributionModelingBeyondSimple';
import GapSalesMethodologyPlaybooksMeddicSandler from './pages/GapSalesMethodologyPlaybooksMeddicSandler';
import GapVoiceCallCoachingPostCall from './pages/GapVoiceCallCoachingPostCall';
import GapWorkflowApprovalGatesComplianceReview from './pages/GapWorkflowApprovalGatesComplianceReview';

const ProtectedRoute: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user, loading } = useAuth();

  if (loading) {
    return (
      <div className="loading">
        <div className="spinner"></div>
      </div>
    );
  }

  if (!user) {
    return <Navigate to="/login" replace />;
  }

  return <>{children}</>;
};

const AppRoutes: React.FC = () => {
  const { user } = useAuth();

  return (
    <Routes>
        <Route path="/codex/custom-viz" element={<ProtectedRoute><CodexCustomVizFeature /></ProtectedRoute>} />
        <Route path="/codex/operations" element={<ProtectedRoute><CodexOperationsFeature /></ProtectedRoute>} />

      <Route path="/login" element={user ? <Navigate to="/" replace /> : <Login />} />
      <Route path="/password-reset" element={<PasswordReset />} />
      <Route
        path="/*"
        element={
          <ProtectedRoute>
            <Layout>
              <Routes>
                <Route path="/" element={<Dashboard />} />
                <Route path="/campaigns" element={<Campaigns />} />
                <Route path="/campaigns/:id" element={<CampaignDetail />} />
                <Route path="/contacts" element={<Contacts />} />
                <Route path="/contacts/:id" element={<ContactDetail />} />
                <Route path="/templates" element={<Templates />} />
                <Route path="/templates/:id" element={<TemplateDetail />} />
                <Route path="/analytics" element={<Analytics />} />
                <Route path="/ab-tests" element={<ABTests />} />
                <Route path="/ab-tests/:id" element={<ABTestDetail />} />
                <Route path="/integrations" element={<Integrations />} />
                <Route path="/integrations/:id" element={<IntegrationDetail />} />
                <Route path="/team" element={<Team />} />
                <Route path="/team/:id" element={<TeamMemberDetail />} />
                <Route path="/ai-assistant" element={<AIAssistant />} />
                <Route path="/sequences" element={<Sequences />} />
                <Route path="/sequences/:id" element={<SequenceDetail />} />
                <Route path="/meetings" element={<Meetings />} />
                <Route path="/meetings/:id" element={<MeetingDetail />} />
                <Route path="/tasks" element={<Tasks />} />
                <Route path="/tasks/:id" element={<TaskDetail />} />
                <Route path="/reports" element={<Reports />} />
                <Route path="/reports/:id" element={<ReportDetail />} />
                <Route path="/notifications" element={<Notifications />} />
                <Route path="/settings" element={<Settings />} />
                <Route path="/ai/lead-scores" element={<AILeadScorer />} />
                <Route path="/ai/lead-scores/:id" element={<AILeadScoreDetail />} />
                <Route path="/ai/personalizations" element={<AIPersonalization />} />
                <Route path="/ai/personalizations/:id" element={<AIPersonalizationDetail />} />
                <Route path="/ai/best-times" element={<AIBestTime />} />
                <Route path="/ai/best-times/:id" element={<AIBestTimeDetail />} />
                <Route path="/ai/objections" element={<AIObjections />} />
                <Route path="/ai/objections/:id" element={<AIObjectionDetail />} />
                <Route path="/ai/forecasts" element={<AIPipelineForecast />} />
                <Route path="/ai/forecasts/:id" element={<AIPipelineForecastDetail />} />
                <Route path="/ai/warmup" element={<AIWarmupScheduler />} />
                <Route path="/ai/competitive-intel" element={<AICompetitiveIntel />} />
                <Route path="/ai/playbook" element={<AIPlaybookLearner />} />
                <Route path="/ai/prospect-research" element={<AIProspectResearch />} />
                <Route path="/ai/deal-momentum" element={<AIDealMomentum />} />
                <Route path="/ai/objection-predictor" element={<AIObjectionPredictor />} />
                <Route path="/ai/reply-triage" element={<AIReplyTriage />} />
                <Route path="/deals" element={<Deals />} />
                <Route path="/custom-views" element={<CustomViewsPage />} />
                {/* Apply pass 7: Gap pages */}
                <Route path="/gap/ai-account-tier-scoring-icp" element={<GapAiAccountTierScoringIcp />} />
                <Route path="/gap/ai-competitor-win-loss-analysis" element={<GapAiCompetitorWinLossAnalysis />} />
                <Route path="/gap/ai-live-conversation-coaching-calls" element={<GapAiLiveConversationCoachingCalls />} />
                <Route path="/gap/ai-multilingual-outreach-generation" element={<GapAiMultilingualOutreachGeneration />} />
                <Route path="/gap/auto-generated-competitor-battlecards-web" element={<GapAutoGeneratedCompetitorBattlecardsWeb />} />
                <Route path="/gap/deeper-enrichment-salesforce-einstein-linkedin" element={<GapDeeperEnrichmentSalesforceEinsteinLinkedin />} />
                <Route path="/gap/limited-custom-field-automation-data" element={<GapLimitedCustomFieldAutomationData />} />
                <Route path="/gap/multi-channel-asset-library-video" element={<GapMultiChannelAssetLibraryVideo />} />
                <Route path="/gap/qbr-executive-summary-builder" element={<GapQbrExecutiveSummaryBuilder />} />
                <Route path="/gap/real-time-meeting-transcript-analysis" element={<GapRealTimeMeetingTranscriptAnalysis />} />
                <Route path="/gap/revenue-attribution-modeling-beyond-simple" element={<GapRevenueAttributionModelingBeyondSimple />} />
                <Route path="/gap/sales-methodology-playbooks-meddic-sandler" element={<GapSalesMethodologyPlaybooksMeddicSandler />} />
                <Route path="/gap/voice-call-coaching-post-call" element={<GapVoiceCallCoachingPostCall />} />
                <Route path="/gap/workflow-approval-gates-compliance-review" element={<GapWorkflowApprovalGatesComplianceReview />} />
              </Routes>
            </Layout>
          </ProtectedRoute>
        }
      />
    </Routes>
  );
};

const App: React.FC = () => {
  return (
    <ErrorBoundary>
      <AuthProvider>
        <ToastProvider>
          <AppRoutes />
        </ToastProvider>
      </AuthProvider>
    </ErrorBoundary>
  );
};

export default App;
